### ISSUE TITLE
Where are datasets and models？

### ISSUE THREAD

**Issue by zhouhao-learning** [shenieee09/Tensorflow-Object-Detection---Strange-pig-motions#1]
Hello, I'm glad to see your sharing, but I don't have datasets, and I don't know how to reproduce your results. Can you tell me how to obtain datasets and models you have trained? thank you

**Comment by jtong99** [comment]
Sorry, I know it late but my dataset is provided privately by the company. So I cannot share it! Thanks for asking me

btw, you can preview this link: https://github.com/tensorflow/models/tree/master/research/object_detection to learn more about Object detection API.
